// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eotjevfbubbkazedpwky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvdGpldmZidWJia2F6ZWRwd2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzM2OTUsImV4cCI6MjA3MDA0OTY5NX0.QAR_vGeA1Hjd3JCBogP6HCXESo-LT7jpO2wkneO4r2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});